# Generated by Django 4.2.5 on 2023-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Detail', models.CharField(max_length=200)),
                ('On_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
